### ISSUE TITLE
Downloading (and caching) assets locally instead of hotlinking

### ISSUE THREAD

**Issue by eitchtee** [silexlabs/eleventy-plugin-directus#3]
I was wondering the best way of downloading directus' assets and storing them locally instead of hotlinking to my directus instance using `directus_asseturl`

internet2000.net already seems to do this (e.g. https://internet2000.net/optimized/8a7c9b06-0d80-4b3b-9624-ebcb359e8ea3-235.webp and https://internet2000.net/uploads/93c3b71f-16fc-4a88-b883-b7be02a1e919.svg).

After a few hours of tinkering (JS is not my strong suit), I came up with a hacky solution using Eleventy-Fetch that seems to work, although it could be greatly improved:

`filters/directus_asset.js`

```javascript
const fs = require('fs');
const EleventyFetch = require("@11ty/eleventy-fetch");


module.exports = async function (img) {
    const directus_c = this.ctx.directus // from https://github.com/11ty/eleventy/issues/813

    let url = `${directus_c.url}/assets/${img.filename_disk}?download&access_token=${directus_c.token}`;

    let imageBuffer = await EleventyFetch(url, {
        duration: "1d",
        type: "buffer"
    });

    let folder_path = `./public/img/${img.folder.name}/`
    let path = `${folder_path}${img.filename_download}`
    fs.mkdirSync(folder_path, { recursive: true })
    fs.writeFile(path, imageBuffer, "binary", (err) => err && console.error(err))

    let final_path = `/img/${img.folder.name}/${img.filename_download}`
    return final_path;
};
```

`.eleventy.js`

```javascript
...
  eleventyConfig.addAsyncFilter('directus_asset', require('./filters/directus_download.js'));
...
```

`template.njk`

```njk
{% for cliente in directus.collections.Clientes %}
      <div><img src="{{ cliente.Logo | directus_asset }}" alt="{{ cliente.Nome }}"></div>
{% endfor %}
```

---

I'm not sure if this is the best way of doing this, but I was wondering if it would be possible to share how Internet2000 does it or implement a native function for doing this within the plugin.

**Comment by lexoyo** [comment]
Hello
That's an interesting way of doing it and it seems ok to me
I'll share how we do it tomorrow but in the meantime I can tell you that I share directus asset folder with eleventy which then access it with the file name as you did for the url

**Comment by lexoyo** [comment]
I checked in our code and I use sharp to load images from file system and optimise them, then put them in 11ty's folder

I want to refactor this code, it is really old, but here is where I load an image and make it a webp

```js
      const loaded = sharp(localPath, { failOnError: false })
      await loaded.toFile(path.join(optimizedDestPath, fileName + '.webp'))
      metadata = await loaded.metadata()
```


Do I answer your question?

**Comment by eitchtee** [comment]
Quite clever setup, albeit a bit non-usable for myself.

Thanks a lot for sharing.

I think if there aren't plans for implementing a native function for doing it, this issue can be closed and left as recourse for others stumbling on the same problem.

**Comment by lexoyo** [comment]
Ok thank you

Why isn't it usable for you? If you have ideas on what to do let me know, I'll put some more work into this plugin soon

**Comment by eitchtee** [comment]
> Why isn't it usable for you?

My Directus instance is located in another VM from my 11ty site, so mounting the uploads folder directly into it sounds like more trouble than it's worth.

---

If you think it's within scope, my suggestion would be a properly coded native filter for downloading the images.

`directus_asseturl` already works great, but poses some problems, for example, if you don't want to give public access to your uploads on Directus, the link won't work at all. Also, mounting the Directus folder directly might work for some setups and not for others as mentioned above, so there's always some degree of hacking evolved, which a native filter could gracefully fix.

---

Forgot to mention, but this plugin saved my live, so simple to use and really useful. Thank you very much for your work!

**Comment by lexoyo** [comment]
Oh thank you for the feedback
I'll integrate such a filter in the next version i think, it's a good idea
Or maybe i'll just write a doc on how to plug this plugin with https://www.11ty.dev/docs/plugins/image/
It's great that it was useful to you :D 
Bye :hand:
